# This is a simple Travis config for a project that only needs to install pure
# Python dependencies. For more complex setups, you can use conda on Travis:
# http://conda.pydata.org/docs/travis.html 

language: python
python:
  - "3.5"
  - "3.4"
services:
  - redis-server --port 6200
  - redis-server --port 6201
  - redis-server --port 6202
  - redis-server --port 6203
# Install any dependencies for running the tests:
install: pip install -r requirements.txt && python setup.py build_ext  --inplace
# command to run tests
script: py.test --cov=remcdbg --cov-config .coveragerc remcdbg/tests/*.py 
after_success:
  codecov

