sudo: required  
cache: pip
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
services:
  - docker
before_install:
  - docker build --build-arg TRAVIS=true -t phelimb/bigsi .
script:
  - sudo docker run phelimb/bigsi /bin/sh -c "TRAVIS=true py.test -s -vv --cov=bigsi --cov-config .coveragerc bigsi/tests/"
after_success:
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";  
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push phelimb/bigsi;
    else
    docker tag phelimb/bigsi:latest phelimb/bigsi:"$TRAVIS_BRANCH-$COMMIT";
    docker push phelimb/bigsi:"$TRAVIS_BRANCH-$COMMIT";
    docker tag phelimb/bigsi:latest phelimb/bigsi:"$TRAVIS_BRANCH";
    docker push phelimb/bigsi:"$TRAVIS_BRANCH";    
    fi

