version: '2'

services:
  main:
    image: phelimb/atlasseq
    ports:
      - "5000:5000"      
    links:
      
        - redis1:redis1
      
        - redis2:redis2
      
    environment:
      
        - REDIS_IP_1=redis1
        - REDIS_PORT_1=6301
      
        - REDIS_IP_2=redis2
        - REDIS_PORT_2=6302
                
    volumes:
        - "$DATA_DIR:/data"                   
    command: tail -f /etc/hosts
  worker:  
    image: phelimb/atlasseq
    command: sh run_celery.sh   
    depends_on:
        - redisbroker            
    links:
      
        - redis1:redis1
      
        - redis2:redis2
      
    environment:
        - C_FORCE_ROOT="yes" 
      
        - REDIS_IP_1=redis1
        - REDIS_PORT_1=6301
      
        - REDIS_IP_2=redis2
        - REDIS_PORT_2=6302
      
    volumes:
        - "$DATA_DIR:/data"      
  
  redis1:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6301    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6301  
  
  redis2:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6302    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6302  
  

  redisbroker:  
    image: redis
    command: redis-server --appendonly yes    
    volumes:
      - redis-data:/data       

volumes:
  redis-data:
    driver: local

  

