version: '2'

services:
  main:
    image: phelimb/atlasseq
    ports:
      - "5000:5000"      
      - "8000:8000"      
    environment:
        - REDIS_IP_1=127.0.0.1
        - REDIS_PORT_1=7000         
        - "BFSIZE=$BFSIZE"
        - "NUM_HASHES=$NUM_HASHES"
        - "BULK_CMD_OUTDIR=$BULK_CMD_OUTDIR"
        - "STORAGE=$STORAGE"
        - "BDB_DB_FILENAME=$BDB_DB_FILENAME"        
    volumes:
        - "$DATA_DIR:/data"                   
    network_mode: "host"  

  strictredis:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6379    
    ports:
      - 6379  
    volumes_from:
      - "redismanager"      
    network_mode: "host"      
  
  redis1:
    image: phelimb/redis-cluster
    environment:
        - PORT=7000    
    volumes_from:
      - "redismanager"
    ports:
      - 7000  
    network_mode: "host"  

  
  redis2:
    image: phelimb/redis-cluster
    environment:
        - PORT=7001    
    volumes_from:
      - "redismanager"
    ports:
      - 7001  
    network_mode: "host"  

  
  redis3:
    image: phelimb/redis-cluster
    environment:
        - PORT=7002    
    volumes_from:
      - "redismanager"
    ports:
      - 7002  
    network_mode: "host"  

  


  redismanager:
    image: phelimb/redis-trib                   
    volumes:
      - "$DATA_DIR:/data"               
    command: tail -f /etc/hosts
    network_mode: "host"   

volumes:
  redis-data:
    driver: local

  

