version: '2'

services:
  main:
    image: phelimb/atlasseq
    ports:
      - "5000:5000"      
    links:
      
        - redis1:redis1
      
        - redis2:redis2
      
        - redis3:redis3
      
        - redis4:redis4
      
        - redis5:redis5
      
        - redis6:redis6
      
        - redis7:redis7
      
        - redis8:redis8
      
        - redis9:redis9
      
        - redis10:redis10
      
        - redis11:redis11
      
        - redis12:redis12
      
        - redis13:redis13
      
        - redis14:redis14
      
        - redis15:redis15
      
        - redis16:redis16
      
        - redis17:redis17
      
        - redis18:redis18
      
        - redis19:redis19
      
        - redis20:redis20
      
    environment:
      
        - REDIS_IP_1=redis1
        - REDIS_PORT_1=6301
      
        - REDIS_IP_2=redis2
        - REDIS_PORT_2=6302
      
        - REDIS_IP_3=redis3
        - REDIS_PORT_3=6303
      
        - REDIS_IP_4=redis4
        - REDIS_PORT_4=6304
      
        - REDIS_IP_5=redis5
        - REDIS_PORT_5=6305
      
        - REDIS_IP_6=redis6
        - REDIS_PORT_6=6306
      
        - REDIS_IP_7=redis7
        - REDIS_PORT_7=6307
      
        - REDIS_IP_8=redis8
        - REDIS_PORT_8=6308
      
        - REDIS_IP_9=redis9
        - REDIS_PORT_9=6309
      
        - REDIS_IP_10=redis10
        - REDIS_PORT_10=6310
      
        - REDIS_IP_11=redis11
        - REDIS_PORT_11=6311
      
        - REDIS_IP_12=redis12
        - REDIS_PORT_12=6312
      
        - REDIS_IP_13=redis13
        - REDIS_PORT_13=6313
      
        - REDIS_IP_14=redis14
        - REDIS_PORT_14=6314
      
        - REDIS_IP_15=redis15
        - REDIS_PORT_15=6315
      
        - REDIS_IP_16=redis16
        - REDIS_PORT_16=6316
      
        - REDIS_IP_17=redis17
        - REDIS_PORT_17=6317
      
        - REDIS_IP_18=redis18
        - REDIS_PORT_18=6318
      
        - REDIS_IP_19=redis19
        - REDIS_PORT_19=6319
      
        - REDIS_IP_20=redis20
        - REDIS_PORT_20=6320
                
    volumes:
        - "$DATA_DIR:/data"                   
    command: tail -f /etc/hosts
  worker:  
    image: phelimb/atlasseq
    command: sh run_celery.sh   
    depends_on:
        - redisbroker            
    links:
      
        - redis1:redis1
      
        - redis2:redis2
      
        - redis3:redis3
      
        - redis4:redis4
      
        - redis5:redis5
      
        - redis6:redis6
      
        - redis7:redis7
      
        - redis8:redis8
      
        - redis9:redis9
      
        - redis10:redis10
      
        - redis11:redis11
      
        - redis12:redis12
      
        - redis13:redis13
      
        - redis14:redis14
      
        - redis15:redis15
      
        - redis16:redis16
      
        - redis17:redis17
      
        - redis18:redis18
      
        - redis19:redis19
      
        - redis20:redis20
      
    environment:
        - C_FORCE_ROOT="yes" 
      
        - REDIS_IP_1=redis1
        - REDIS_PORT_1=6301
      
        - REDIS_IP_2=redis2
        - REDIS_PORT_2=6302
      
        - REDIS_IP_3=redis3
        - REDIS_PORT_3=6303
      
        - REDIS_IP_4=redis4
        - REDIS_PORT_4=6304
      
        - REDIS_IP_5=redis5
        - REDIS_PORT_5=6305
      
        - REDIS_IP_6=redis6
        - REDIS_PORT_6=6306
      
        - REDIS_IP_7=redis7
        - REDIS_PORT_7=6307
      
        - REDIS_IP_8=redis8
        - REDIS_PORT_8=6308
      
        - REDIS_IP_9=redis9
        - REDIS_PORT_9=6309
      
        - REDIS_IP_10=redis10
        - REDIS_PORT_10=6310
      
        - REDIS_IP_11=redis11
        - REDIS_PORT_11=6311
      
        - REDIS_IP_12=redis12
        - REDIS_PORT_12=6312
      
        - REDIS_IP_13=redis13
        - REDIS_PORT_13=6313
      
        - REDIS_IP_14=redis14
        - REDIS_PORT_14=6314
      
        - REDIS_IP_15=redis15
        - REDIS_PORT_15=6315
      
        - REDIS_IP_16=redis16
        - REDIS_PORT_16=6316
      
        - REDIS_IP_17=redis17
        - REDIS_PORT_17=6317
      
        - REDIS_IP_18=redis18
        - REDIS_PORT_18=6318
      
        - REDIS_IP_19=redis19
        - REDIS_PORT_19=6319
      
        - REDIS_IP_20=redis20
        - REDIS_PORT_20=6320
      
    volumes:
        - "$DATA_DIR:/data"      
  
  redis1:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6301    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6301  
  
  redis2:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6302    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6302  
  
  redis3:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6303    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6303  
  
  redis4:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6304    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6304  
  
  redis5:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6305    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6305  
  
  redis6:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6306    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6306  
  
  redis7:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6307    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6307  
  
  redis8:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6308    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6308  
  
  redis9:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6309    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6309  
  
  redis10:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6310    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6310  
  
  redis11:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6311    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6311  
  
  redis12:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6312    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6312  
  
  redis13:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6313    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6313  
  
  redis14:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6314    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6314  
  
  redis15:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6315    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6315  
  
  redis16:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6316    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6316  
  
  redis17:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6317    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6317  
  
  redis18:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6318    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6318  
  
  redis19:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6319    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6319  
  
  redis20:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6320    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6320  
  

  redisbroker:  
    image: redis
    command: redis-server --appendonly yes    
    volumes:
      - redis-data:/data       

volumes:
  redis-data:
    driver: local

  

