version: '2'

services:
  main:
    image: phelimb/remcdbg
    ports:
      - "8001"      
    links:
      
        - redis1:redis1
      
        - redis2:redis2
      
        - redis3:redis3
      
        - redis4:redis4
      
        - redis5:redis5
      
        - redis6:redis6
      
        - redis7:redis7
      
        - redis8:redis8
      
        - redis9:redis9
      
        - redis10:redis10
      
        - redis11:redis11
      
        - redis12:redis12
      
        - redis13:redis13
      
        - redis14:redis14
      
        - redis15:redis15
      
        - redis16:redis16
      
        - redis17:redis17
      
        - redis18:redis18
      
        - redis19:redis19
      
        - redis20:redis20
      
        - redis21:redis21
      
        - redis22:redis22
      
        - redis23:redis23
      
        - redis24:redis24
      
        - redis25:redis25
      
        - redis26:redis26
      
        - redis27:redis27
      
        - redis28:redis28
      
        - redis29:redis29
      
        - redis30:redis30
      
        - redis31:redis31
      
        - redis32:redis32
      
        - redis33:redis33
      
        - redis34:redis34
      
        - redis35:redis35
      
        - redis36:redis36
      
        - redis37:redis37
      
        - redis38:redis38
      
        - redis39:redis39
      
        - redis40:redis40
      
        - redis41:redis41
      
        - redis42:redis42
      
        - redis43:redis43
      
        - redis44:redis44
      
        - redis45:redis45
      
        - redis46:redis46
      
        - redis47:redis47
      
        - redis48:redis48
      
        - redis49:redis49
      
        - redis50:redis50
      
        - redis51:redis51
      
        - redis52:redis52
      
        - redis53:redis53
      
        - redis54:redis54
      
        - redis55:redis55
      
        - redis56:redis56
      
        - redis57:redis57
      
        - redis58:redis58
      
        - redis59:redis59
      
        - redis60:redis60
      
        - redis61:redis61
      
        - redis62:redis62
      
        - redis63:redis63
      
        - redis64:redis64
      
    environment:
      
        - REDIS_IP_1=redis1
        - REDIS_PORT_1=6301
      
        - REDIS_IP_2=redis2
        - REDIS_PORT_2=6302
      
        - REDIS_IP_3=redis3
        - REDIS_PORT_3=6303
      
        - REDIS_IP_4=redis4
        - REDIS_PORT_4=6304
      
        - REDIS_IP_5=redis5
        - REDIS_PORT_5=6305
      
        - REDIS_IP_6=redis6
        - REDIS_PORT_6=6306
      
        - REDIS_IP_7=redis7
        - REDIS_PORT_7=6307
      
        - REDIS_IP_8=redis8
        - REDIS_PORT_8=6308
      
        - REDIS_IP_9=redis9
        - REDIS_PORT_9=6309
      
        - REDIS_IP_10=redis10
        - REDIS_PORT_10=6310
      
        - REDIS_IP_11=redis11
        - REDIS_PORT_11=6311
      
        - REDIS_IP_12=redis12
        - REDIS_PORT_12=6312
      
        - REDIS_IP_13=redis13
        - REDIS_PORT_13=6313
      
        - REDIS_IP_14=redis14
        - REDIS_PORT_14=6314
      
        - REDIS_IP_15=redis15
        - REDIS_PORT_15=6315
      
        - REDIS_IP_16=redis16
        - REDIS_PORT_16=6316
      
        - REDIS_IP_17=redis17
        - REDIS_PORT_17=6317
      
        - REDIS_IP_18=redis18
        - REDIS_PORT_18=6318
      
        - REDIS_IP_19=redis19
        - REDIS_PORT_19=6319
      
        - REDIS_IP_20=redis20
        - REDIS_PORT_20=6320
      
        - REDIS_IP_21=redis21
        - REDIS_PORT_21=6321
      
        - REDIS_IP_22=redis22
        - REDIS_PORT_22=6322
      
        - REDIS_IP_23=redis23
        - REDIS_PORT_23=6323
      
        - REDIS_IP_24=redis24
        - REDIS_PORT_24=6324
      
        - REDIS_IP_25=redis25
        - REDIS_PORT_25=6325
      
        - REDIS_IP_26=redis26
        - REDIS_PORT_26=6326
      
        - REDIS_IP_27=redis27
        - REDIS_PORT_27=6327
      
        - REDIS_IP_28=redis28
        - REDIS_PORT_28=6328
      
        - REDIS_IP_29=redis29
        - REDIS_PORT_29=6329
      
        - REDIS_IP_30=redis30
        - REDIS_PORT_30=6330
      
        - REDIS_IP_31=redis31
        - REDIS_PORT_31=6331
      
        - REDIS_IP_32=redis32
        - REDIS_PORT_32=6332
      
        - REDIS_IP_33=redis33
        - REDIS_PORT_33=6333
      
        - REDIS_IP_34=redis34
        - REDIS_PORT_34=6334
      
        - REDIS_IP_35=redis35
        - REDIS_PORT_35=6335
      
        - REDIS_IP_36=redis36
        - REDIS_PORT_36=6336
      
        - REDIS_IP_37=redis37
        - REDIS_PORT_37=6337
      
        - REDIS_IP_38=redis38
        - REDIS_PORT_38=6338
      
        - REDIS_IP_39=redis39
        - REDIS_PORT_39=6339
      
        - REDIS_IP_40=redis40
        - REDIS_PORT_40=6340
      
        - REDIS_IP_41=redis41
        - REDIS_PORT_41=6341
      
        - REDIS_IP_42=redis42
        - REDIS_PORT_42=6342
      
        - REDIS_IP_43=redis43
        - REDIS_PORT_43=6343
      
        - REDIS_IP_44=redis44
        - REDIS_PORT_44=6344
      
        - REDIS_IP_45=redis45
        - REDIS_PORT_45=6345
      
        - REDIS_IP_46=redis46
        - REDIS_PORT_46=6346
      
        - REDIS_IP_47=redis47
        - REDIS_PORT_47=6347
      
        - REDIS_IP_48=redis48
        - REDIS_PORT_48=6348
      
        - REDIS_IP_49=redis49
        - REDIS_PORT_49=6349
      
        - REDIS_IP_50=redis50
        - REDIS_PORT_50=6350
      
        - REDIS_IP_51=redis51
        - REDIS_PORT_51=6351
      
        - REDIS_IP_52=redis52
        - REDIS_PORT_52=6352
      
        - REDIS_IP_53=redis53
        - REDIS_PORT_53=6353
      
        - REDIS_IP_54=redis54
        - REDIS_PORT_54=6354
      
        - REDIS_IP_55=redis55
        - REDIS_PORT_55=6355
      
        - REDIS_IP_56=redis56
        - REDIS_PORT_56=6356
      
        - REDIS_IP_57=redis57
        - REDIS_PORT_57=6357
      
        - REDIS_IP_58=redis58
        - REDIS_PORT_58=6358
      
        - REDIS_IP_59=redis59
        - REDIS_PORT_59=6359
      
        - REDIS_IP_60=redis60
        - REDIS_PORT_60=6360
      
        - REDIS_IP_61=redis61
        - REDIS_PORT_61=6361
      
        - REDIS_IP_62=redis62
        - REDIS_PORT_62=6362
      
        - REDIS_IP_63=redis63
        - REDIS_PORT_63=6363
      
        - REDIS_IP_64=redis64
        - REDIS_PORT_64=6364
                
    volumes:
        - "$DATA_DIR:/data"                   
    command: bash -c "cat /etc/hosts && env && tail -F -n0 /etc/hosts"
  
  redis1:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6301    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6301  
  
  redis2:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6302    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6302  
  
  redis3:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6303    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6303  
  
  redis4:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6304    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6304  
  
  redis5:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6305    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6305  
  
  redis6:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6306    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6306  
  
  redis7:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6307    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6307  
  
  redis8:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6308    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6308  
  
  redis9:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6309    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6309  
  
  redis10:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6310    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6310  
  
  redis11:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6311    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6311  
  
  redis12:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6312    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6312  
  
  redis13:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6313    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6313  
  
  redis14:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6314    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6314  
  
  redis15:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6315    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6315  
  
  redis16:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6316    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6316  
  
  redis17:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6317    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6317  
  
  redis18:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6318    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6318  
  
  redis19:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6319    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6319  
  
  redis20:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6320    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6320  
  
  redis21:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6321    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6321  
  
  redis22:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6322    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6322  
  
  redis23:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6323    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6323  
  
  redis24:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6324    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6324  
  
  redis25:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6325    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6325  
  
  redis26:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6326    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6326  
  
  redis27:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6327    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6327  
  
  redis28:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6328    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6328  
  
  redis29:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6329    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6329  
  
  redis30:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6330    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6330  
  
  redis31:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6331    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6331  
  
  redis32:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6332    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6332  
  
  redis33:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6333    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6333  
  
  redis34:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6334    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6334  
  
  redis35:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6335    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6335  
  
  redis36:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6336    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6336  
  
  redis37:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6337    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6337  
  
  redis38:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6338    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6338  
  
  redis39:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6339    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6339  
  
  redis40:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6340    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6340  
  
  redis41:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6341    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6341  
  
  redis42:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6342    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6342  
  
  redis43:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6343    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6343  
  
  redis44:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6344    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6344  
  
  redis45:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6345    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6345  
  
  redis46:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6346    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6346  
  
  redis47:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6347    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6347  
  
  redis48:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6348    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6348  
  
  redis49:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6349    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6349  
  
  redis50:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6350    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6350  
  
  redis51:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6351    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6351  
  
  redis52:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6352    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6352  
  
  redis53:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6353    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6353  
  
  redis54:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6354    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6354  
  
  redis55:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6355    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6355  
  
  redis56:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6356    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6356  
  
  redis57:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6357    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6357  
  
  redis58:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6358    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6358  
  
  redis59:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6359    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6359  
  
  redis60:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6360    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6360  
  
  redis61:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6361    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6361  
  
  redis62:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6362    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6362  
  
  redis63:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6363    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6363  
  
  redis64:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=6364    
    volumes:
      - "$DATA_DIR:/data"
    ports:
      - 6364  
    

  

