version: '2'

services:
  main:
    image: phelimb/atlasseq
    ports:
      - "5000:5000"      
      - "8000:8000"      
    environment:
        - REDIS_IP_1=127.0.0.1
        - REDIS_PORT_1=7001          
    volumes:
        - "$DATA_DIR:/data"                   
    network_mode: "host"  

  strictredis:
    image: redis
    environment:
        - PORT=6379    
    volumes:
      - "$DATA_DIR:/datastrict"
    ports:
      - 6379  
    network_mode: "host"      
  
  redis1:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=7001    
    volumes:
      - "$DATA_DIR:/dataredis1"
    ports:
      - 7001  
    network_mode: "host"  

  
  redis2:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=7002    
    volumes:
      - "$DATA_DIR:/dataredis2"
    ports:
      - 7002  
    network_mode: "host"  

  
  redis3:
    image: phelimb/redis-mcdbg
    environment:
        - PORT=7003    
    volumes:
      - "$DATA_DIR:/dataredis3"
    ports:
      - 7003  
    network_mode: "host"  

  

  redisbroker:  
    image: redis
    command: redis-server --appendonly yes    
    volumes:
      - redis-data:/data   

  redismanager:
    image: phelimb/redis-trib                   
    volumes:
        - "$DATA_DIR:/data"                   
    command: tail -f /etc/hosts
    network_mode: "host"           

volumes:
  redis-data:
    driver: local

  

