h: 3
k: 31
m: 25000000
max_build_mem_bytes: "20GB"
low_mem_build: false
storage-engine: rocksdb
storage-config:
  filename: test-rocksdb
  options:
    create_if_missing: true
    max_open_files: 5000
